### ISSUE TITLE
where is jdbc-sink.properties

### ISSUE THREAD

**Issue by SerhiiNesteruk** [ibm-messaging/kafka-connect-jdbc-sink#40]
`Copy the connect-standalone.properties and jdbc-sink.properties files into the /usr/local/etc/kafka/ directory.`

`connect-standalone.properties` is in cofig directory. Where can I get `jdbc-sink.properties`

**Comment by AdrianGV** [comment]
Same problem here, jdbc-sink.properties does not exist

**Comment by chriscrossman-ibm** [comment]
This jdbc-sink.properties file has been added to the /config directory.
